#!/bin/bash

pgsql_show_help() {
  echo "This script creates a new BDR enabled database."
  echo ""
  echo "Usage: pgsql_create_bdr_db -d bdr_test -o postgres -n node1 -ip 127.0.0.1 -p 5433"
  echo ""
  echo "-a, --authenticate           A flag to indicate to the script that it should authenticate with postgresql."
  echo "-d, --database               The new database name."
  echo "-o, --owner                  The new database owner."
  echo "-u, --user                   The postgresql user used to create the database."
  echo ""
  echo "BDR Options:"
  echo "-j, --join                  A flag indicating to the script that it should join a group and not create one."
  echo ""
  echo "-n, --name                  The local node name."
  echo "-ip, --address              The local address."
  echo "-p, --port                  The local port."
  echo ""
  echo "-rip, --remote_address      The address to the remote host where the BDR group was created."
  echo "-rp, --remote_port          The port on the remote host where the BDR group was created."
}

pgsql_create_bdr_db() {
  sudo -u postgres psql -U postgres -d postgres \
       -c "CREATE DATABASE $2 OWNER $3;"
  sudo -u postgres psql -U postgres -d $2 \
       -c "CREATE EXTENSION btree_gist; \
           CREATE EXTENSION bdr;"
  sudo -u postgres psql -U postgres -d $2 \
       -c "SELECT bdr.bdr_group_create( \
           local_name := '$6', \
           node_external_dsn := 'host=$7 port=$8 dbname=$2' \
          ); \
          SELECT bdr.bdr_node_join_wait_for_ready();"
}

authenticate=0
database=
owner=
user=
join_group=0
name=
address=
port=
remote_address=
remote_port=
while :; do
  case $1 in
    -\?|--help)
      pgsql_show_help
      exit
      ;;
    -a|--authenticate)
      authenticate=1
      shift
      ;;
    -d|--database)
      if [ -n "$2" ]; then
        database="$2"
        shift
      else
        printf 'ERROR: "--database" requires a valid name.\n' >&2
        exit 1
      fi
      ;;
    -o|--owner)
      if [ -n "$2" ]; then
        owner="$2"
        shift
      else
        printf 'ERROR: "--owner" requires a valid name.\n' >&2
        exit 1
      fi
      ;;
    -u|--user)
      if [ -n "$2" ]; then
        user="$2"
        shift
      else
        printf 'ERROR: "--user" requires a valid user.\n' >&2
        exit 1
      fi
      ;;
    -n|--name)
      if [ -n "$2" ]; then
        name="$2"
        shift
      else
        printf 'ERROR: "--name" requires a valid name.\n' >&2
        exit 1
      fi
      ;;
    -j|--join)
      join_group=1
      shift
    -ip|--address)
      if [ -n "$2" ]; then
        address="$2"
        shift
      else
        printf 'ERROR: "--address" requires a valid address.\n' >&2
        exit 1
      fi
      ;;
    -p|--port)
      if [ -n "$2" ]; then
        port="$2"
        shift
      else
        printf 'ERROR: "--port" requires a valid port number.\n' >&2
        exit 1
      fi
      ;;
    -rip|--remote_address)
      if [ -n "$2" ]; then
        remote_address="$2"
        shift
      else
        printf 'ERROR: "--remote_address requires a valid address.\n' >&2
        exit 1
      fi
      ;;
    -rp|--remote_port)
      if [ -n "$2" ]; then
        remote_port="$2"
        shift
      else
        printf 'ERROR: "--remote_port requires a valid port.\n' >&2
        exit 1
      ;;
    --)
      shift
      break
      ;;
    -?*)
      printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
      ;;
    *)
      break
  esac
  shift
done

if [ -n "$database" ] && \
   [ -n "$owner" ] && \
   [ -n "$user" ] && \
   [ -n "$name" ] && \
   [ -n "$address" ] && \
   [ -n "$port" ]; then
  pgsql_create_bdr_db $authenticate \
                      $database \
                      $owner \
                      $user \
                      $join_group \
                      $name \
                      $address \
                      $port \
                      $remote_address \
                      $remote_port
else
  pgsql_show_help
fi
